import { describe, it, expect } from "vitest";

import { leaderPersonalities } from "../../leaderPersonalities.js";

// The AI's personality table. Every leader is generated by drawing each trait
// uniformly from its personality's [min, max], so a malformed range silently
// produces a leader whose trait is NaN or inverted -- and the AI then scores
// every goal against it.
//
// This is data integrity, not rule behaviour: the scoring itself becomes a unit
// test when `ai/` is extracted in refactor Phase 5.5.

const TRAITS = ["fortification", "economy", "territory_expansion", "style_of_war", "reconquista"];

const personalities = leaderPersonalities.personalities;

describe("leaderPersonalities", () => {
    it("defines at least one personality", () => {
        expect(Array.isArray(personalities)).toBe(true);
        expect(personalities.length).toBeGreaterThan(0);
    });

    it("gives every personality a unique id", () => {
        const ids = personalities.map((personality) => personality.id);
        expect(new Set(ids).size).toBe(ids.length);
        expect(ids.every((id) => typeof id === "string" && id.length > 0)).toBe(true);
    });

    it("gives every personality all five traits", () => {
        const incomplete = personalities
            .filter((personality) => TRAITS.some((trait) => !personality[trait]))
            .map((personality) => personality.id);

        expect(incomplete).toEqual([]);
    });

    it("keeps every trait range inside 0..1 with min <= max", () => {
        const bad = [];
        for (const personality of personalities) {
            for (const trait of TRAITS) {
                const range = personality[trait];
                if (!range) continue;
                if (!Number.isFinite(range.min) || !Number.isFinite(range.max)) {
                    bad.push(`${personality.id}.${trait}: non-numeric`);
                    continue;
                }
                if (range.min < 0 || range.max > 1) {
                    bad.push(
                        `${personality.id}.${trait}: [${range.min}, ${range.max}] out of 0..1`
                    );
                }
                if (range.min > range.max) {
                    bad.push(`${personality.id}.${trait}: min ${range.min} > max ${range.max}`);
                }
            }
        }

        expect(bad).toEqual([]);
    });

    it("offers meaningfully different personalities, not five copies", () => {
        // If every personality had the same ranges the leader traits would carry no
        // information and `prioritiseTurnGoalsBasedOnPersonality` would be a no-op.
        const signatures = personalities.map((personality) =>
            TRAITS.map((trait) => `${personality[trait]?.min}-${personality[trait]?.max}`).join("|")
        );

        expect(new Set(signatures).size).toBe(personalities.length);
    });
});
